tasks:
# Terraform tool
  - name: Terraform
    before: |
      ./bin/terraform_cli_install.sh

# CDK install
  - name: cdk
    before: |
      npm i -g aws-cdk

# Random utilities
  - name: utils
    before: |
      sudo apt-get install tree

# AWS CLI for autocomplete
  - name: AWS CLI
    env:
      AWS_CLI_AUTO_PROMPT: on-partial
    before: |
       ./bin/aws_cli_install.sh
      

