version=0.1
[default.package.parameters]
s3_bucket = "obako2"
region = "us-east-1"
image_repository = "365897511972.dkr.ecr.us-east-1.amazonaws.com/python-container-sample"
[default.deploy.parameters]
s3_bucket = "obako2"
region = "us-east-1"
image_repository = "365897511972.dkr.ecr.us-east-1.amazonaws.com/python-container-sample"
